spring:
  datasource: # = DATA SOURCE
    url: jdbc:postgresql://localhost/toauth
    username: gustavoparro
    password: gustavoparro
    driver-class-name: org.postgresql.Driver
  jpa: # = JPA / HIBERNATE
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect