spring:
  datasource: # = DATA SOURCE
    url: jdbc:postgresql://localhost/toauth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari: # = CONNECTION POOL
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 10000
  jpa: # = JPA / HIBERNATE
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect